// Theme switch test. Run: node tests/look.mjs  (needs the site on http://localhost:8000)
import { createRequire } from 'node:module';
import { execSync } from 'node:child_process';
const require = createRequire(import.meta.url);
const { chromium } = require(execSync('npm root -g').toString().trim() + '/playwright');
const BASE = process.env.BASE || 'http://localhost:8000';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await browser.newContext({ viewport: { width: 375, height: 700 } });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
let failed = 0;
const check = (name, ok) => { console.log((ok ? 'PASS ' : 'FAIL ') + name); if (!ok) failed++; };
const look = () => page.evaluate(() => document.body.dataset.look);

await page.goto(BASE + '/?preview=1');
await page.waitForSelector('#door');
await page.waitForSelector('#stage:not(.busy)');
check('look: defaults to the dreamy night sky', (await look()) === 'night');
check('look: night sky is drawn (stars and a night door)', (await page.locator('#sky i').count()) > 40 && (await page.locator('.night-door').count()) === 1);
await page.click('#look');
await page.waitForFunction(() => document.body.dataset.look === 'scrapbook');
await page.waitForSelector('#stage:not(.busy)');
await page.waitForFunction(() => !document.querySelector('.night-door'), null, { timeout: 8000 });
check('look: switching gives the scrapbook diary (and redraws the door)', (await look()) === 'scrapbook' && (await page.locator('.night-door').count()) === 0 && (await page.locator('.door-svg').count()) === 1);
check('look: the choice is remembered', (await page.evaluate(() => localStorage.getItem('look'))) === 'scrapbook');
await page.reload();
await page.waitForSelector('#door');
check('look: still scrapbook after a reload', (await look()) === 'scrapbook');
await page.goto(BASE + '/?preview=1&look=night');
await page.waitForSelector('#door');
check('look: ?look=night overrides the saved choice', (await look()) === 'night');
await page.click('#look');
await page.waitForFunction(() => document.body.dataset.look === 'scrapbook');
await page.click('#look');
await page.waitForFunction(() => document.body.dataset.look === 'night');
await page.waitForSelector('#stage:not(.busy)');
check('look: can switch back and forth', (await look()) === 'night');
check('no JS errors', errors.length === 0);
if (errors.length) console.log(errors);
await browser.close();
process.exit(failed ? 1 : 0);
